---
default_stages: [commit, manual]
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.32.0'
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
      - id: mypy
        additional_dependencies:
          - pygame

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-crlf

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: migrations/
