# USAGE:
# This works whether you've ever installed this environment before or not,
# and whether dependencies have been added, changed, or removed since last run.
#
#   conda env update --file=environment.yml --prune
#
---
name: ai-final
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - rich
      - pygame
      - pytest
      - pytest-timeout
      - pre-commit
      - mypy
      - types-PyYAML
      - flake8
      - flake8-bugbear
      - flake8-comprehensions
      - flake8-pyi
      - black
      - nb_black  # run black auto-formatter in jupyter notebook
      - jupyterlab  # run python/markdown notebooks
      - jupyterlab-lsp  # language server protocol client for jupyterlab
      - jedi-language-server  # language server for python
